### ISSUE TITLE
Why do you compile this seperately ?

### ISSUE THREAD

**Issue by InsaneMiner** [pradosh-arduino/PradoshOS#3]
https://github.com/pradosh-arduino/PradoshOS/blob/2353d340fc07e3d0ad6ab15a9a30929bcf4aed9f/kernel/Makefile#L57

Why does this get compiled separately?

**Comment by pradosh-arduino** [comment]
No issues are answered. due to discontinuation of PradoshOS

**Comment by InsaneMiner** [comment]
> No issues are answered. due to discontinuation of PradoshOS

ok
